name: lint
on: [ push ]
jobs:
  linter_name:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Format Check
        run: |
          python3 -m pip install --upgrade black isort
          python3 -m black .
          python3 -m isort .
