name: test
on: [ push ]
jobs:
  linter_name:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Unit Tests
        run: |
          python3 manage.py test
